### PR TITLE
add overload of the operator|() for the VFilters for pipeline syntax

### PR DESCRIPTION
**Pull request by alexsvetlichnyy**
Can we move in filterAnsamble from unique_ptr to shared_ptr?

### CODE REVIEW

**Comment by apBUSampK** [comment]
> Can we move in filterAnsamble from unique_ptr to shared_ptr?

Yes, we can.

**Comment by apBUSampK** [comment]
However, it's not needed. We can just use const links for operator|. This way you don't need to copy the smart pointer at all and, therefore, don't really need shared_ptr. 

The use case for shared_ptr is multiple objects having ownership of a resource. In our case, operator| functions do not own it.

**Comment by alexsvetlichnyy** [comment]
using a unique_ptr leads to the calling a deleted object (aka functor) in the function operator|. Using const link does not solve this problem, because ptr is deleted before |

**Comment by apBUSampK** [comment]
> using a unique_ptr leads to the calling a deleted object (aka functor) in the function operator|. Using const link does not solve this problem, because ptr is deleted before |

I'm not sure what do you mean. Consider this example:

```
#include <memory>
#include <iostream>

void print_unique(const std::unique_ptr<int>& in) {
	std::cout << *in << std::endl;
}
int main() {
	auto var = std::make_unique<int>(9);
	print_unique(var);
	std::cout << *var << std::endl;
	return 0;
}
```
Here the unique_ptr reference works inside the function and the ownership doesn't change, so the created ptr may be used again in main. I can't see the difference between this example and the code in question.

**Comment by apBUSampK** [comment]
Even better, really, we should pass raw pointers to the functions, since the objects' ownership doesn't change at all.

**Pull request merged**
